### ISSUE TITLE
Add to AUR

### ISSUE THREAD

**Issue by Kommynct** [lostutils/suex#12]
I'd do it if I knew how, I might look into it tonight, but this would be very helpful.

thank you for all the hard work man.

**Comment by Risen-phoenix** [comment]
I'm willing to add this package to the AUR as soon as I track down its deps. If anyone has a list of the Arch package names required, that would make my job a lot easier.

**Comment by odedlaz** [comment]
I'm thinking about moving away from packaging in different formats and using `snap` and `flatpak` instead.

what do you guys think? @Risen-phoenix @that1communist

**Comment by Risen-phoenix** [comment]
I don't use either one personally. But that's just me I'm sure.

**Comment by ecesar88** [comment]
> I'm thinking about moving away from packaging in different formats and using `snap` and `flatpak` instead.
> 
> what do you guys think? @Risen-phoenix @that1communist

I don't use either one too... Never used, tbh. I think a native package would be better. I was looking into your blog post and really liked the syntax of the rules and the intuitive arguments, besides the simplicity of the program. It'll be god to have it on AUR, ASAP. Congrats for the hard work! And keep on!

**Comment by Kommynct** [comment]
opendoas is in the actual repos now, closing this
